### ISSUE TITLE
deleteE not working for 1 node LL

### ISSUE THREAD

**Issue by zakhaev26** [punitkr03/labprogs#1]
> In Semester 2/lab4/prog1.c

 deleteE isn't giving the desired o/p for 1 Node...

```   
node* deleteE(node* head) {
    node* temp = head;
    if(*(temp).next==NULL){ free(temp);return 0;}
    while(temp->next->next != NULL) {
        temp = temp->next;
    }
    node* temp2 = temp->next;
    temp->next = NULL;
    free(temp2);
    return head;
}

```
Also the code crashes on 0 nodes input...Causing Segmentation Error..

**Comment by punitkr03** [comment]
Code is not meant to be robust. It's only for lab purpose. That's why it's like that. You can edit it as your preferences😀

**Comment by zakhaev26** [comment]
![image](https://github.com/punitkr03/labprogs/assets/119437069/9a39bc00-ead9-4a50-ac2e-511320073855)
